# Generated by Django 5.0.6 on 2024-07-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
